# Generated by Django 4.0.3 on 2022-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('Name', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=1024)),
            ],
        ),
    ]
